#!/bin/bash
export CLICOLOR=1
export HISTCONTROL="ignoredups"
export HISTSIZE="2000"
export LSCOLORS=dxFxCxDxBxegedabagacad

export EDITOR="vim"
export VISUAL="vim"
export PAGER=less
export BLOCKSIZE=K
export PARINIT='w72jrT4bgqR B=.,?_A_a Q=_s>|'
export LC_CTYPE=en_US.UTF-8
export VIM_APP_DIR=/Applications
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;33'

export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWCOLORHINTS=1
export GIT_PS1_DESCRIBE_STYLE="branch"
export GIT_PS1_SHOWUPSTREAM="auto git"

export LESS="-X -M -E -R"
# export LESSOPEN="| $HOME/bin/lesspipe.sh %s"
export LS_OPTIONS="--color=yes  -F -b -T 0"

export PATH=~/.rbenv/shims:$PATH
export PATH=~/bin:$PATH

[ $TERM = "screen" ] && export TERM=xterm


